In [1]:
from qem.fitting import ImageModelFitting
import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
import os
# sys.path.append('/home/zzhang/OneDrive/code/hyperspy/hyperspy')
%matplotlib qt

file = '/home/zzhang/OneDrive/data/High_entropy/script/adf_avg.npy'
# s = hs.load(file)
image = np.load(file)
dx = 0.36254824166962796

model=ImageModelFitting(image, dx=dx,units='A')
model.find_peaks(min_distance=int(2/dx))
cif_file = '/home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_conventional_standard.cif'
model.map_lattice(cif_file=cif_file,elements=['Sr','Ti'],min_distance=20,a_limit=50, b_limit=50 )

Updated peak locations.
Origin selected: [342. 147.]
Vector a selected: [11. -1.]
Vector b selected: [  0. -11.]
In pixel: Origin: [342. 147.], Vector a: [11. -1.], Vector b: [  0. -11.]
In space: Origin: [123.99149865  53.29459153] A, Vector a: [ 3.98803066 -0.36254824] A, Vector b: [ 0.         -3.98803066] A
Origin selected: [360. 128.]
Vector a selected: [65. -1.]
Vector b selected: [ 3. 25.]
In pixel: Origin: [360. 128.], Vector a: [65. -1.], Vector b: [ 3. 25.]
In space: Origin: [1.37912681 0.4903562 ] 1/A, Vector a: [ 0.24900901 -0.00383091] 1/A, Vector b: [0.01149272 0.0957727 ] 1/A
FFT real a: [11.05651106 -0.47174447] pixel, Real b: [ 0.44226044 10.22113022] pixel


In [1]:
from qem.image_model import ImageModelFitting
import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
import os
# sys.path.append('/home/zzhang/OneDrive/code/hyperspy/hyperspy')
%matplotlib qt

file = '/home/zzhang/OneDrive/code/qem/data/high_entropy/adf_avg.npy'
# s = hs.load(file)
image = np.load(file)
dx = 0.36254824166962796

model=ImageModelFitting(image, dx=dx,units='A')

# get the unique coordinates by row
# input_coordinates = np.unique(input_coordinates, axis=0)

In [2]:
model.find_peaks(min_distance=4)

Updated peak locations.


array([[152., 185.],
       [152., 216.],
       [151.,  92.],
       ...,
       [707., 160.],
       [707.,  76.],
       [713., 161.]])

In [3]:
model.find_peaks(min_distance=4)
cif_file = '/home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_conventional_standard.cif'
model.map_lattice(cif_file=cif_file,elements=['Sr','Ti'],min_distance=20,a_limit=50, b_limit=50 )
# model.select_region(invert_selection=False)

Updated peak locations.
Origin selected: [343. 189.]
Vector a selected: [10. -1.]
Vector b selected: [ -1. -11.]
In pixel: Origin: [343. 189.], Vector a: [10. -1.], Vector b: [ -1. -11.]
In space: Origin: [124.35404689  68.52161768] A, Vector a: [ 3.62548242 -0.36254824] A, Vector b: [-0.36254824 -3.98803066] A
Origin selected: [360. 128.]
Vector a selected: [65. -1.]
Vector b selected: [ 3. 25.]
In pixel: Origin: [360. 128.], Vector a: [65. -1.], Vector b: [ 3. 25.]
In space: Origin: [3.87879415 1.37912681] 1/A, Vector a: [ 0.70033783 -0.01077443] 1/A, Vector b: [0.03232328 0.26936071] 1/A
FFT real a: [11.05622332 -0.47839428] pixel, Real b: [ 0.43611275 10.22139252] pixel


In [4]:
model.select_region()

INFO:root:Selected 2731 atoms out of 3176 atoms.


In [6]:
model.add_or_remove_peaks(min_distance=4)

INFO:root:Adding peak at (509.0790946564308, 215.69816208448358) with atom type 0.
INFO:root:Adding peak at (518.3367431834512, 212.97532428241877) with atom type 0.
INFO:root:Removing peak at (534.436112747638, 212.22139252276745).
INFO:root:Adding peak at (530.3172295125364, 211.34162160117987) with atom type 0.
INFO:root:Adding peak at (519.4258783042771, 223.32210793026508) with atom type 0.
INFO:root:Adding peak at (530.3172295125364, 221.14383768861322) with atom type 0.
INFO:root:Removing peak at (534.8722254952761, 222.4427850455349).
INFO:root:Adding peak at (535.2183375562531, 226.58951329274285) with atom type 0.
INFO:root:Removing peak at (525.7461680360639, 227.871499122152).
INFO:root:Current atom type set to 1.
INFO:root:Adding peak at (529.2280943917104, 230.94605377604657) with atom type 1.
INFO:root:Adding peak at (524.3269863479937, 217.33186476572246) with atom type 1.
INFO:root:Removing peak at (540.1822807837019, 217.09289164491943).
INFO:root:Adding peak at (535.

Updated peak locations.


array([[  2.75469049,   6.12146539],
       [  3.19080323,  16.34285792],
       [  3.62691598,  26.56425044],
       ...,
       [589.6750936 , 233.66889158],
       [592.3979314 , 243.47110767],
       [580.96201263, 245.10481035]])

In [7]:

model.fit_background = True
params = model.init_params()
model.fit_random_batch(params, batch_size=1000, maxiter=50, tol=1e-3, plot=False, step_size=0.01,verbose=False,num_epoch=5)

Fitting random batch:   0%|          | 0/3 [00:00<?, ?it/s]INFO:jax._src.xla_bridge:Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA
INFO:jax._src.xla_bridge:Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
Fitting random batch: 100%|██████████| 3/3 [00:06<00:00,  2.07s/it]
INFO:root:Convergence rate for pos_x = 0.5901207095866283
INFO:root:Convergence rate for pos_y = 0.5927822986629891
INFO:root:Convergence rate for height = 7.93564647757098e-05
INFO:root:Convergence rate for sigma = 0.005659952993221096
INFO:root:Convergence not reached
Fitting random batch: 100%|██████████| 3/3 [00:02<00:00,  1.05it/s]
INFO:root:Convergence rate for pos_x = 0.589080810546875
INFO:root:Convergence rate for pos_y = 0.5767059326171875
INFO:root:Convergence rate for height = 7.5676392462892e-05
INFO:root:Convergence rate for 

{'pos_x': array([  5.15470791,   3.41256118,   3.99286604, ..., 590.32421875,
        591.33990479, 579.94830322]),
 'pos_y': array([  3.58374786,  14.80955887,  26.81474495, ..., 233.74407959,
        244.14985657, 244.53128052]),
 'height': array([3203.20270608, 2940.99160319, 3239.57077135, ..., 4552.39455066,
        4039.51739448, 4417.38816369]),
 'sigma': array([1.88407992, 1.88407992, 1.88407992, ..., 1.88407992, 1.88407992,
        1.94874211]),
 'background': 31459.20667385557}

In [3]:
from qem.crystal_analyzer import CrystalAnalyzer

crystal_analyzer = CrystalAnalyzer(image = model.image, dx = model.dx, peak_positions = model.coordinates, atom_types = model.atom_types, elements=['Sr','Ti'],units=model.units)
cif_file = '/home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_conventional_standard.cif'
crystal_analyzer.read_cif(cif_file)
crystal_analyzer.choose_lattice_vectors(tolerance=20)
supercell_in_image, supercell_atom_types = crystal_analyzer.generate_supercell_lattice(a_limit=20, b_limit=20)

Origin selected: [343. 189.]
Vector a selected: [10. -1.]
Vector b selected: [ -1. -11.]
In pixel: Origin: [343. 189.], Vector a: [10. -1.], Vector b: [ -1. -11.]
In space: Origin: [124.35404689  68.52161768] A, Vector a: [ 3.62548242 -0.36254824] A, Vector b: [-0.36254824 -3.98803066] A
Origin selected: [360. 128.]
Vector a selected: [65. -1.]
Vector b selected: [ 3. 25.]
In pixel: Origin: [360. 128.], Vector a: [65. -1.], Vector b: [ 3. 25.]
In space: Origin: [3.87879415 1.37912681] 1/A, Vector a: [ 0.70033783 -0.01077443] 1/A, Vector b: [0.03232328 0.26936071] 1/A
FFT real a: [11.05622332 -0.47839428] pixel, Real b: [ 0.43611275 10.22139252] pixel


In [4]:
peaks = crystal_analyzer.shift_origin_adaptive(20,20)

plt.imshow(model.image)
for key, value in peaks.items():
    plt.scatter(value[0], value[1])

In [11]:
params = model.params

In [12]:
#save parameters dict 
np.save('params.npy',params)

In [ ]:
model_edx = 

In [7]:
model.plot_scs()

In [8]:
model.plot_fitting()

In [5]:
model.plot_coordinates()

In [1]:
from qem.crystal_analyzer import CrystalAnalyzer
from qem.image_model import ImageModelFitting
import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
%matplotlib qt

file = '/home/zzhang/OneDrive/code/qem/data/STO/adf_average_STO.txt'
image = np.loadtxt(file)
dx= 0.1645429228960236	
model=ImageModelFitting(image, dx=dx,units='A')
model.find_peaks()
crystal_analyzer = CrystalAnalyzer(image = model.image, dx = model.dx, peak_positions = model.coordinates, atom_types = model.atom_types, elements=['Sr','Ti'])

INFO:numexpr.utils:Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.


Updated peak locations.


INFO:root:No atoms selected.


In [6]:

cif_file = '/home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_conventional_standard.cif'
crystal_analyzer.read_cif(cif_file)

Atoms(symbols='SrTi', pbc=True, cell=[3.905, 3.905, 3.905], spacegroup_kinds=...)

In [4]:
crystal_analyzer.choose_lattice_vectors()

Selection incomplete.
Selection incomplete.


TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'

In [5]:
crystal_analyzer._origin_adaptive = None
shift_center = crystal_analyzer.shift_origin_adaptive(50, 50)
plt.imshow(model.image, cmap='gray')
peaks = []
for key, value in shift_center.items():
    peaks.append(value)

plt.scatter(np.array(peaks)[:,0], np.array(peaks)[:,1], c='r', s=10)
plt.show()

In [6]:
peak_positions, atom_types = crystal_analyzer.generate_supercell_lattice(a_limit=50, b_limit=50)

In [14]:
peak_positions, atom_types = crystal_analyzer.supercell_project_2d()

In [7]:
plt.scatter(peak_positions[:,0], peak_positions[:,1], c='r', s=10)

In [10]:
crystal_analyzer.unitcell_mapping()

TypeError: list indices must be integers or slices, not numpy.float64

In [23]:
im_refined = model.predict_local(params=model.params)
plt.imshow(im_refined)

In [25]:
plt.imshow(model.image-im_refined)

In [18]:
model.atom_types

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,