In [48]:
from qem.image_fitting import ImageModelFitting
import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
import hyperspy.api as hs
%matplotlib qt

# file = '/home/zzhang/OneDrive/code/qem/data/STO/adf_average_STO.txt'

# image = np.loadtxt(file)
# file = '/home/zzhang/OneDrive/data/Nico/28.03.2024-STOonSTO21mrad/83-100/aligned_hdf5/1859 HAADF 33.7 nm.emd.hspy'
file = '/home/zzhang/OneDrive/code/qem/data/STO/restore_hdf5/Scanning Preview6_1.hspy'
# file ='/home/zzhang/OneDrive/data/Nico/28.03.2024-STOonSTO21mrad/84-100/aligned_hdf5/1932 HAADF 33.7 nm.emd.hspy'

s = hs.load(file)
image = s.data
# image = np.load(file)
# dx= 0.1645429228960236	
dx = s.axes_manager[1].scale *10
# dx = 0.36254824166962796
model=ImageModelFitting(image, dx=dx,units='A')

# get the unique coordinates by row
# input_coordinates = np.unique(input_coordinates, axis=0)

INFO:root:Elements: ['Sr', 'Ti', 'O'], the order is used for the atom types. Please initiate the correct elements in your system.


In [4]:
model.plot(vmin=13000)

In [8]:
model.find_peaks(min_distance=10,threshold_abs=10600,threshold_rel=0.05)

INFO:root:Updated peak locations.


array([[1117., 1955.],
       [1650., 1675.],
       [1662.,  842.],
       ...,
       [  21.,   21.],
       [ 254.,    7.],
       [ 885.,   29.]])

In [6]:
model.assign_region_label(1)

AttributeError: 'GetRegionSelection' object has no attribute 'path'

In [5]:
model.plot_region()

In [49]:
cif_file = '/home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_conventional_standard.cif'

model.find_peaks(min_distance=9,threshold_abs=12600,threshold_rel=0.1,region_index=0)
model.map_lattice(cif_file=cif_file,elements=['Sr','Ti'], reciprocal=True,region_index=0)

INFO:root:Updated peak locations.
/home/zzhang/OneDrive/code/qem/qem/gui_classes.py:361: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('x').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  plt.scatter(
INFO:root:Origin selected: [1153. 1324.]
INFO:root:Vector a selected: [22.  0.]
INFO:root:Vector b selected: [ -1. -23.]
INFO:root:In pixel: Origin: [1153. 1324.], Vector a: [22.  0.], Vector b: [ -1. -23.]
INFO:root:In space: Origin: [205.24881488 235.68901206] A, Vector a: [3.91628268 0.        ] A, Vector b: [-0.17801285 -4.09429553] A
INFO:root:Origin selected: [1024. 1024.]
INFO:root:Vector a selected: [92. -1.]
INFO:root:Vector b selected: [ -2. -91.]
INFO:root:In pixel: Origin: [1024. 1024.], Vector a: [92. -1.], Vector b: [ -2. -91.]
INFO:root:In space: Origin: [2.80878601 2.80878601] 1/A, Vector a: [ 0.25235187 -0.00274296] 1/A, Vector b: [-0.00548591 -0.24960891] 1/A
INFO:root:FFT rea

AtomicColumns(lattice=Atoms(symbols='Sr7325Ti7358', pbc=False, cell=[364.5703147256795, 364.5703147256795, 3.905], spacegroup_kinds=...), lattice_ref=Atoms(symbols='Sr7325Ti7358', pbc=False, cell=[[2.7447050062989122, 399.8245452770462, 0.0], [5.29254324078289, 397.70957432514524, 0.0], [0.0, 0.0, 3.905]], spacegroup_kinds=...), elements=['Sr', 'Ti'], tol=0, pixel_size=0.1780128489871482)

In [ ]:
from ase.visualize import view
view(model.region_atomic_column[0].lattice)

In [14]:
model.add_or_remove_peaks(min_distance=10)

INFO:root:Adding peak at (454.03803339517617, 924.1159554730982) with atom type 0.
INFO:root:Removing peak at (454.03803339517617, 924.1159554730982).
INFO:root:Removing peak at (444.0081512108683, 940.5054918527459).
INFO:root:Updated peak locations.


array([[1.77531483e+00, 4.62300011e+02],
       [3.41558277e+00, 1.19516501e+03],
       [4.00000000e+00, 1.81800000e+03],
       ...,
       [2.04700815e+03, 1.90350549e+03],
       [2.04700815e+03, 1.94850549e+03],
       [2.04729892e+03, 1.35592298e+03]])

In [50]:
model.select_atoms()

INFO:root:Selected 14432 atoms out of 14683 atoms.


In [51]:
model.plot_coordinates(10)

In [52]:
model.fit_background = True
params = model.init_params()
model.fit_random_batch(params, batch_size=1000, maxiter=50, tol=1e-3, plot=False, step_size=0.01,verbose=False,num_epoch=5)

Fitting random batch: 100%|██████████| 15/15 [01:33<00:00,  6.24s/it]
INFO:root:Convergence rate for pos_x = 0.9697629060121926
INFO:root:Convergence rate for pos_y = 0.9373142147126146
INFO:root:Convergence rate for height = 0.0005701949451856896
INFO:root:Convergence rate for sigma = 0.08237148914427979
INFO:root:Convergence not reached
Fitting random batch: 100%|██████████| 15/15 [01:33<00:00,  6.26s/it]
INFO:root:Convergence rate for pos_x = 0.5556640625
INFO:root:Convergence rate for pos_y = 0.563934326171875
INFO:root:Convergence rate for height = 0.0005212323727038352
INFO:root:Convergence rate for sigma = 0.06004269583993079
INFO:root:Convergence not reached
Fitting random batch: 100%|██████████| 15/15 [01:33<00:00,  6.22s/it]
INFO:root:Convergence rate for pos_x = 0.551483154296875
INFO:root:Convergence rate for pos_y = 0.54913330078125
INFO:root:Convergence rate for height = 0.00048299938953291343
INFO:root:Convergence rate for sigma = 0.04368066291614314
INFO:root:Convergenc

{'pos_x': array([6.16352320e-01, 4.85905796e-01, 6.82925284e-01, ...,
        2.04700000e+03, 2.04700000e+03, 2.04543982e+03]),
 'pos_y': array([1886.67260742, 1908.85229492, 1931.64025879, ..., 1331.62353516,
        1353.89404297, 1376.03808594]),
 'height': array([1463.33162697, 1565.96057302, 1489.80933526, ..., 1168.37076285,
        1119.89953594, 1035.39962717]),
 'sigma': array([4.90816854, 5.21813257]),
 'background': 14329.36221133978}

In [53]:
model.plot_fitting()

In [27]:
plt.figure()
plt.hist(model.volume[model.atom_types==0], bins=100, alpha=0.5,label='Sr')
plt.hist(model.volume[model.atom_types==1], bins=100, alpha=0.5,label='Ti')
plt.legend()

In [54]:
model.plot_scs(per_element=True)

In [56]:
model.plot_scs_histogram()

In [58]:
model.voronoi_integration()

Integrating: 100%|██████████| 14432/14432 [01:51<00:00, 129.33it/s]              


(array([4278.21352888, 4514.1230821 , 4363.743962  , ..., 3232.74928103,
        3143.82643748, 3611.29232602]),
 <Signal2D, title: , dimensions: (|2048, 2048)>,
 <Signal2D, title: , dimensions: (|2048, 2048)>)

In [59]:
model.plot_scs_voronoi()

In [63]:
model.params['pos_x']

array([6.16352320e-01, 4.85905796e-01, 6.82925284e-01, ...,
       2.04700000e+03, 2.04700000e+03, 2.04543982e+03])

In [65]:
model.region_crysal_analyzer[0].lattice.positions

array([[2.05248815e+02, 2.35689012e+02, 0.00000000e+00],
       [2.07208407e+02, 2.33642842e+02, 1.95250000e+00],
       [2.01154519e+02, 2.35689012e+02, 0.00000000e+00],
       ...,
       [5.90636600e+00, 1.54379088e+00, 0.00000000e+00],
       [2.93679783e-02, 3.58819339e+00, 1.95250000e+00],
       [1.94397925e+00, 1.58686827e+00, 0.00000000e+00]])

In [62]:
model.region_crysal_analyzer[0].peak_positions =

array([[1.37817015e-01, 9.70034248e+02],
       [1.64976733e-01, 2.01569348e+01],
       [3.81963377e-01, 9.92469957e+02],
       ...,
       [2.04736442e+03, 1.33261198e+03],
       [2.04754982e+03, 1.35510997e+03],
       [2.04796976e+03, 1.37785812e+03]])