In [1]:
import hyperspy.api as hs
import numpy as np
from qem.image_fitting import ImageModelFitting
import cv2

%matplotlib qt

file = '/home/zzhang/OneDrive/code/qem/data/SRO-CTO/ABF time step .hspy'
s = hs.load(file)
dx = s.axes_manager[1].scale *10 # convert nm to Angstrom
dx = 0.05431373318394167 # Angstrom, calculated from fft

image = s.data[-1000:,50:-50]
image = image - image.min()

from scipy import ndimage


image = image.max() - image
model=ImageModelFitting(image, dx=dx,units='A')
model.calibrate(cif_file='/home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_110.cube.cif')

INFO:root:Elements: ['A', 'B', 'C'], the order is used for the atom types. Please initiate the correct elements in your system.
INFO:root:Updated peak locations.
INFO:root:Reading CIF file: /home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_110.cube.cif. The elements selected are ['A', 'B', 'C'] and the elements in the CIF file are OTiO


TypeError: cannot unpack non-iterable NoneType object

In [1]:
import hyperspy.api as hs
import numpy as np
from qem.image_fitting import ImageModelFitting
import cv2

%matplotlib qt

# file = '../data/STO/haadf_small.hspy'

file = '/home/zzhang/OneDrive/code/qem/data/SRO-CTO/ABF time step .hspy'
# file = '/home/zzhang/OneDrive/data/Nico/SRO-CTO Superlattice/9-45/restore_hdf5/ADF time step .hspy'
# file = '/home/zzhang/OneDrive/code/qem/examples/superlattice_adf.h5'
s = hs.load(file)
dx = s.axes_manager[1].scale *10 # convert nm to Angstrom
dx = 0.05431373318394167 # Angstrom, calculated from fft

image = s.data[50:-50,50:-50]
image = image - image.min()

# rotate the image by 45 degrees
from scipy import ndimage

# theta = 45
# rotated_image = ndimage.rotate(image, theta, reshape=False, mode='constant')

# Replace the original image with the rotated one
# image = rotated_image[:,1200:2800]

image = image.max() - image
model=ImageModelFitting(image, dx=dx,units='A')
# model.plot() # inspect the image

INFO:root:Elements: ['A', 'B', 'C'], the order is used for the atom types. Please initiate the correct elements in your system.


In [2]:
model.find_peaks(min_distance=10,threshold_rel=0.05)

INFO:root:Updated peak locations.


array([[2109., 1784.],
       [ 518., 2429.],
       [ 672., 2429.],
       ...,
       [3586.,  207.],
       [  65.,  861.],
       [3891.,  207.]])

In [3]:
cif_file = '/home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_110.vasp' 
# cif_file ='/home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_conventional_standard.cif'
model.map_lattice(cif_file=cif_file,elements=['Sr','Ti','O'], reciprocal=True,region_index=0) # map the cif unitcell to the image and tile it according the local peak positions

INFO:root:Reading CIF file: /home/zzhang/OneDrive/code/qem/data/STO/SrTiO3_mp-5229_110.vasp. The elements selected are ['Sr', 'Ti', 'O'] and the elements in the CIF file are SrTiO3
/home/zzhang/OneDrive/code/qem/qem/gui_classes.py:371: UserWarning: You passed a edgecolor/edgecolors ('black') for an unfilled marker ('x').  Matplotlib is ignoring the edgecolor in favor of the facecolor.  This behavior may change in the future.
  plt.scatter(
INFO:root:Origin selected: [1887. 3104.]
INFO:root:Vector a selected: [51.  0.]
INFO:root:Vector b selected: [ 1. 71.]
INFO:root:In pixel: Origin: [1887. 3104.], Vector a: [51.  0.], Vector b: [ 1. 71.]
INFO:root:In space: Origin: [102.49001452 168.5898278 ] A, Vector a: [2.77000039 0.        ] A, Vector b: [0.05431373 3.85627506] A
INFO:root:Origin selected: [1998. 1998.]
INFO:root:Vector a selected: [234.   3.]
INFO:root:Vector b selected: [  0. 168.]
INFO:root:In pixel: Origin: [1998. 1998.], Vector a: [78.  1.], Vector b: [ 0. 56.]
INFO:root:In s

AtomicColumns(lattice=Atoms(symbols='O13059Sr4411Ti4340', pbc=False, cell=[217.0376778030309, 217.0376778030309, 2.7612519264]), lattice_ref=Atoms(symbols='O13059Sr4411Ti4340', pbc=False, cell=[217.0376778030309, 217.0376778030309, 2.7612519264]), elements=['Sr', 'Ti', 'O'], tol=0, pixel_size=0.05431373318394167, reference={'origin': array([1887., 3104.]), 'vector_a': array([50.83474961, -0.65172756]), 'vector_b': array([ 0.92168196, 71.89119323])})

In [4]:


model.regions[0].analyzer.plot_lattice_parameter_unitcell(boundary_thresh=10,line_plot_direction='b',line_plot_averaging_window=3,line_plot_style='error_bars')

In [6]:
model.plot_coordinates()

In [7]:
model.regions[0].analyzer.plot()

Value(False)
Value(False)


INFO:root:Perfect a: [50.83474961 -0.65172756] pixel, Perfect b: [ 0.92168196 71.89119323] pixel by rotation of unit cell and scaling with pixel size.


IndexError: boolean index did not match indexed array along dimension 0; dimension is 21805 but corresponding boolean dimension is 13072

In [7]:

import matplotlib.pyplot as plt
plt.imshow(model.regions[0].analyzer.image)

In [ ]:
# model.init_params()
model.refine_center_of_mass()

/home/zzhang/OneDrive/code/qem/qem/image_fitting.py:451: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.clf()
Refining center of mass:   0%|          | 0/1674 [00:00<?, ?it/s]/home/zzhang/OneDrive/code/qem/qem/image_fitting.py:455: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.pause(1.0)
Refining center of mass:   0%|          | 0/1674 [00:00<?, ?it/s]


KeyboardInterrupt: 

QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Canno

In [5]:
params = model.init_params()

model.fit_voronoi()


Fitting cells: 100%|██████████| 13075/13075 [01:56<00:00, 112.06it/s]
INFO:root:Convergence rate for pos_x = 10.992489284585314
INFO:root:Convergence not reached
Fitting cells: 100%|██████████| 13075/13075 [01:54<00:00, 114.58it/s]
INFO:root:Convergence rate for pos_x = 0.0
INFO:root:Convergence rate for pos_y = 0.0
INFO:root:Convergence rate for height = 0.0
INFO:root:Convergence rate for sigma = 0.0
INFO:root:Convergence rate for background = 0.0
INFO:root:Convergence reached


{'pos_x': array([   0.        ,    0.        ,    0.        , ..., 3995.46435476,
        3995.46435476, 3995.46435476]),
 'pos_y': array([ 534.        ,  679.        ,  754.        , ..., 2498.67857143,
        2568.67857143, 2710.67857143]),
 'height': array([1845.9471, 1819.7771, 1559.8212, ..., 2088.21  , 1869.807 ,
        1053.3673], dtype=float32),
 'sigma': array([12.88808482, 12.88808482, 12.88808482]),
 'background': 0.0}

In [7]:
model.update_coordinates()

INFO:root:The coordinates have been updated. Current state: 1


array([[   0. , 1894. ],
       [   0. , 1929.5],
       [   0. , 1966. ],
       ...,
       [ 499. , 3891. ],
       [ 499. , 3926.5],
       [ 499.5, 1495.5]])

In [17]:
model.view_3d() # view the 3D model using ase of Atoms object, with coordinates refined from the image

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


In [19]:
model.select_atoms() # select the region where has atoms

INFO:root:Selected 1758 atoms out of 1759 atoms.


array([False,  True,  True, ...,  True,  True,  True])

In [16]:
model.plot_coordinates(10) # plot the coordinates of the selected region with element labels

In [5]:
model.draw_region()

INFO:root:Assigned label 0 with 0 pixels to the region map.


Region 0: init

In [7]:
model.regions.plot_region_map(model.image)

In [ ]:
import os
!export CUDA_VISIBLE_DEVICES=0
os.environ['JAX_PLATFORMS'] = 'gpu'
model.fit_background = False
params = model.init_params(atom_size=0.7)
model.fit_random_batch(params, batch_size=4000, maxiter=50, tol=5e-3, plot=False, step_size=0.01,verbose=False,num_epoch=5) # set the maxiter and tol and num_epoch to be larger for better fitting

In [6]:
model.update_coordinates()
model.update_region_analyzers()

INFO:root:The coordinates have been updated. Current state: 1
INFO:root:Updated region 0 coordinates for crystal analyzer.


In [13]:
model.plot_fitting() # compare the fitting result with the original image

In [30]:
model.plot_scs(per_element=True,s=10) # plot the scattering cross section of the elements in the selected region, show each element separately

In [14]:
model.plot_scs_histogram() # plot the histogram of the scattering cross section of the selected region

In [41]:

model.voronoi_integration(plot=True) # integrate the scattering cross section of the selected region using voronoi tessellation

Integrating: 100%|██████████| 1758/1758 [00:04<00:00, 388.14it/s]                 


(array([ 8174.29485751, 10783.27550203,  7876.22458842, ...,
         2239.57388934,  7408.65695896, 10485.87122523]),
 <Signal2D, title: , dimensions: (|1072, 2972)>,
 <Signal2D, title: , dimensions: (|1072, 2972)>)

In [20]:
model.plot_scs_voronoi(per_element=True,s=20) # plot the scattering cross section of the selected region using voronoi tessellation

Integrating: 100%|██████████| 1674/1674 [00:02<00:00, 700.10it/s]                 


AssertionError: Please run the voronoi analysis first

In [9]:
model.regions[0].analyzer.plot_strain()

/home/zzhang/miniconda3/envs/jax/lib/python3.11/site-packages/matscipy/atomic_strain.py:107: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, residuals, rank, s = np.linalg.lstsq(dr_old[mask], dr_now[mask])


In [18]:
model.regions[0].analyzer.plot_polarization(a_element='Sr', b_element='Ti',cutoff_radius=5.0,exclude_border=True,border_pixel=
100,vector_scale=50.0)

In [14]:
model.regions[0].analyzer.plot_oxygen_tilt(a_type=0, o_type=2)

In [ ]:
# reload qem.crystal_analyzer
# import qem.crystal_analyzer
# import importlib
# importlib.reload(qem.crystal_analyzer)

model.regions[0].analyzer.plot_lattice_parameter_unitcell(boundary_thresh=10,line_plot_direction='b',line_plot_averaging_window=3,line_plot_style='error_bars')

In [21]:

model.regions[0].analyzer.plot_lattice_parameter_nearest(boundary_thresh=10, dist_min_a=2,dist_min_b=3,dist_max_a=3,dist_max_b=4.2,angle_thresh=0.99)

KeyboardInterrupt: 

In [16]:
model.regions[0].analyzer.plot_displacement(mode='local', cut_off = 5.0)

In [18]:
model.regions[0].analyzer.plot_oxygen_tilt(a_type=0, o_type=2, cutoff_radius=5.0)